### ISSUE TITLE
Incorrect questionnaires are being displayed during task chains

### ISSUE THREAD

**Issue by martinburchell** [ucam-department-of-psychiatry/camcops#350]
From CPFT AEDS:

> We've noticed that the incorrect questionnaires are being displayed sometimes during task chains (e.g. if you look at the most recent two patients on the server, the EDE-Q popped up in the middle of the COIIN task chain just now, and earlier today when ---- was getting a patient to do the clinical task chain they were somehow presented with the CHI-T and SUPPS-P).

Some thoughts:

* These task chains are set up with creation method "on demand or abort" so if the task chain was aborted, all of the remaining tasks would have been created. 
* What happens if one task chain is aborted and a different task chain is started?
* ISAAQ-10 prohibits commercial use. What happens if the user hasn't filled in their IP settings?

**Comment by martinburchell** [comment]
One bug here:

* Create a patient on the device
* Don't set any IP settings
* Navigate to Tasks -> Task Chains -> CPFT Adult Eating Disorders Service -> COIIN-AN
* The chain is aborted because ISAAQ-10 prohibits commercial use
* Press the back button
* The user is presented with CHI-T and SUPPS-P

**Comment by RudolfCardinal** [comment]
As a simple fix, perhaps the first step is: (1) Have the chain launcher refuse to start if one of its tasks won't (saying "fix your IP settings first"). I forget if this might ever affect scheduled tasks -- I think not (since you can't schedule a chain?). But if so, perhaps (2) we should have a way of server-to-client transfer of IP settings for single-user mode, so end users don't have to worry?
